[package]
name = "haiku"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.7", features = ["blocking", "json"] }
rocket = "0.5.1"
serde = "1.0.209"
serde_json = "1.0.127"
serde_urlencoded = "0.7.1"
